
services:
  mongo:
    image: mongo:7
    container_name: animania-mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: animania
      MONGO_INITDB_ROOT_PASSWORD: 1XTK-WB3k
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
