import Footer from './components/Footer'
import Header from './components/Header'
import List from './components/List'
import Searchbar from './components/Searchbar'
import TiltCard from './components/TiltCard'
import Home from './templates/Home'
import DetailPage from './templates/DetailPage'
import Card from './components/Card'
import Button from './components/Button'
import useApi from './hooks/useApi'
import Recommendation from './templates/Recommendation'
import Characters from './templates/Characters'
import Trending from './templates/Trending'
import TopRated from './templates/TopRated'
import MostPopular from './templates/MostPopular'
import Airing from './templates/Airing'
import Carousel from './components/Carousel'
import Pagination from './components/Pagination'
import Movies from './templates/Movies'
import Upcoming from './templates/Upcoming'


export { Footer, Header, List, Searchbar, TiltCard, Home, DetailPage, Card, Button, useApi, Recommendation, Characters,Airing, MostPopular, TopRated, Trending, Movies, Upcoming, Carousel, Pagination};